- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml


- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml







- name: Copy service file to remote server
  ansible.builtin.copy:
      src: mongodb.repo     # Path on your Ansible control node
      dest: /etc/yum.repos.d/mongo.repo


- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output



- name: load the products
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout  | int < 0

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes            